version: '3.2'
services:
    las:
      image: registry.scontain.com:5050/sconecuratedimages/services:las
      privileged: true
    redis:
        image: registry.scontain.com:5050/sconecuratedimages/apps:redis-6-alpine-scone4
        command: sh -c "sleep 5; SCONE_LOG=TRACE SCONE_LAS_ADDR=las SCONE_CAS_ADDR=$SCONE_CAS_ADDR SCONE_CONFIG_ID=$REDIS_SESSION/redis redis-server"
        depends_on:
         - las
        ports:
         - "6379"
        environment:
         - SCONE_VERSION=1
    python:
        image: "$IMAGE"
        command: sh -c "sleep 5; SCONE_LOG=TRACE SCONE_LAS_ADDR=las SCONE_CAS_ADDR=$SCONE_CAS_ADDR SCONE_CONFIG_ID=$FLASK_SESSION/flask_restapi python3"
        depends_on:
         - las
        privileged: true
        ports:
         - "4996:4996"
        links:
         - redis
